// <auto-generated />
using System;
using Learly.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Learly.Infrastructure.Migrations
{
    [DbContext(typeof(LearlyDbContext))]
    [Migration("20260422234757_InitialCleanArchitecture")]
    partial class InitialCleanArchitecture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Learly.Domain.Entities.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapituloId")
                        .HasColumnType("int")
                        .HasColumnName("capitulo_id");

                    b.Property<string>("ConteudoDado")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("conteudo_dado");

                    b.Property<DateOnly>("DataAula")
                        .HasColumnType("date")
                        .HasColumnName("data_aula");

                    b.Property<int>("EscolaId")
                        .HasColumnType("int")
                        .HasColumnName("escola_id");

                    b.Property<TimeOnly>("HorarioFim")
                        .HasColumnType("time(6)")
                        .HasColumnName("horario_fim");

                    b.Property<TimeOnly>("HorarioInicio")
                        .HasColumnType("time(6)")
                        .HasColumnName("horario_inicio");

                    b.Property<int>("NumeroAula")
                        .HasColumnType("int")
                        .HasColumnName("numero_aula");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int")
                        .HasColumnName("professor_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("TipoAula")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("tipo_aula");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int")
                        .HasColumnName("turma_id");

                    b.HasKey("Id");

                    b.HasIndex("EscolaId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("TurmaId");

                    b.ToTable("aulas", (string)null);
                });

            modelBuilder.Entity("Learly.Domain.Entities.Escola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CodigoEscola")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("codigo_escola");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CodigoEscola")
                        .IsUnique();

                    b.ToTable("escolas", (string)null);
                });

            modelBuilder.Entity("Learly.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EscolaId")
                        .HasColumnType("int")
                        .HasColumnName("escola_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("nome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EscolaId");

                    b.ToTable("perfis", (string)null);
                });

            modelBuilder.Entity("Learly.Domain.Entities.PerfilPermissao", b =>
                {
                    b.Property<int>("PerfilId")
                        .HasColumnType("int")
                        .HasColumnName("perfil_id");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int")
                        .HasColumnName("permissao_id");

                    b.HasKey("PerfilId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("perfil_permissoes", (string)null);
                });

            modelBuilder.Entity("Learly.Domain.Entities.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("permissoes", (string)null);
                });

            modelBuilder.Entity("Learly.Domain.Entities.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<DateOnly?>("DataTerminoPrevista")
                        .HasColumnType("date")
                        .HasColumnName("data_termino_prevista");

                    b.Property<int>("EscolaId")
                        .HasColumnType("int")
                        .HasColumnName("escola_id");

                    b.Property<TimeOnly?>("Horario")
                        .HasColumnType("time(6)")
                        .HasColumnName("horario");

                    b.Property<int>("LivroId")
                        .HasColumnType("int")
                        .HasColumnName("livro_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("observacoes");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int")
                        .HasColumnName("professor_id");

                    b.Property<string>("Sala")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sala");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EscolaId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("turmas", (string)null);
                });

            modelBuilder.Entity("Learly.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<int>("EscolaId")
                        .HasColumnType("int")
                        .HasColumnName("escola_id");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("nome_completo");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int")
                        .HasColumnName("perfil_id");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("senha");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("EscolaId");

                    b.HasIndex("PerfilId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Learly.Domain.Entities.UsuarioPermissao", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int")
                        .HasColumnName("permissao_id");

                    b.Property<int?>("ConcedidoPorUsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("concedido_por_usuario_id");

                    b.Property<DateTime>("DataConcessao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_concessao");

                    b.HasKey("UsuarioId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("usuario_permissoes", (string)null);
                });

            modelBuilder.Entity("Learly.Domain.Entities.Aula", b =>
                {
                    b.HasOne("Learly.Domain.Entities.Escola", null)
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learly.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learly.Domain.Entities.Turma", null)
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Learly.Domain.Entities.Perfil", b =>
                {
                    b.HasOne("Learly.Domain.Entities.Escola", null)
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Learly.Domain.Entities.PerfilPermissao", b =>
                {
                    b.HasOne("Learly.Domain.Entities.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learly.Domain.Entities.Permissao", null)
                        .WithMany()
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Learly.Domain.Entities.Turma", b =>
                {
                    b.HasOne("Learly.Domain.Entities.Escola", null)
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learly.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Learly.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Learly.Domain.Entities.Escola", null)
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learly.Domain.Entities.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Learly.Domain.Entities.UsuarioPermissao", b =>
                {
                    b.HasOne("Learly.Domain.Entities.Permissao", null)
                        .WithMany()
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learly.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
